-- Generated by nwg-displays on 2026-07-07 at 10:53:51. Do not edit manually.

hl.monitor({
    output = "desc:BNQ BenQ GW2780 K1M0156201Q",
    mode = "1920x1080@60.0",
    position = "2429x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:BNQ BenQ GW2780 K1M0106301Q",
    mode = "1920x1080@60.0",
    position = "509x0",
    scale = 1.0
})
